language: php
services: docker
php:
    - '7.2'
before_install:
  - mkdir $HOME/.local/bin
  - curl -o $HOME/.local/bin/ecs-cli https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest
  - chmod +x $HOME/.local/bin/ecs-cli
  - ecs-cli configure --cluster $CLUSTER_NAME --default-launch-type FARGATE
  - export PATH=$PATH:$HOME/.local/bin
  - export IMAGE_TAG=${TRAVIS_COMMIT::8}
install:
  - docker build -t $DOCKER_REPO:$IMAGE_TAG -f docker/app/Dockerfile .
script:
  - echo "Tests run here!"
after_success:
  - ecs-cli push $DOCKER_REPO:$IMAGE_TAG
  - ecs-cli compose --project-name $PROJECT_NAME service up
